layout_spectrum: 0.9229391
typography_spectrum: 0.7910452
color:
  saturation: 0.1675525
  brandStrength: 0.9012405
  lightness: 0.9689661
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#92AC6D'
    - '#05FDFB'
    - '#91FCFD'
  rhythmicContrast: 0.6540838
name: Entrepreneurship
